### ISSUE TITLE
trace_all.py fails while tracing with "Event checksum error"

### ISSUE THREAD

**Issue by zhuowei** [AsahiLinux/m1n1#109]
When running the hypervisor with trace_all, the trace always fails after a few seconds with "Event checksum error".

M1 Device: Mac Mini, m1n1 d2d5952aa5d8461b6859c6428f543e5791d9f6bf, macOS 12.0b5.

Host running the python shell: macOS 11.6/MacBook Pro 2015

```
python3 run_guest.py -m ../hv/trace_all.py -S /Volumes/thickhd/docs/macos12b5/kernelcache_uncompressed_mac.macho "-v -s cpus=1 debug=0x4 wdt=-1 rd=md0"
```

after some messages

```
Event checksum error: Expected 0x0013ee84, got 0xd0decade
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/shell.py", line 129, in display
    val()
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/hv.py", line 1313, in start
    self.p.hv_start(self.entry, self.guest_base + self.bootargs_off)
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/proxy.py", line 951, in hv_start
    return self.request(self.P_HV_START, entry, *args)
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/proxy.py", line 625, in request
    return self._request(opcode, *args2, **kwargs)
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/proxy.py", line 591, in _request
    reply = self.iface.proxyreq(req, reboot=reboot, no_reply=no_reply, pre_reply=None)
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/proxy.py", line 357, in proxyreq
    return self.reply(self.REQ_PROXY)
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/proxy.py", line 256, in reply
    raise UartChecksumError()
m1n1.proxy.UartChecksumError
```

If I try to start another shell:

```
python3 shell.py 
Event checksum error: Expected 0xd0decade, got 0x66d4435d
Traceback (most recent call last):
  File "shell.py", line 6, in <module>
    from m1n1.setup import *
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/setup.py", line 17, in <module>
    bootstrap_port(iface, p)
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/proxyutils.py", line 447, in bootstrap_port
    do_baud = proxy.iodev_whoami() == IODEV.UART
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/proxy.py", line 928, in iodev_whoami
    return IODEV(self.request(self.P_IODEV_WHOAMI))
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/proxy.py", line 625, in request
    return self._request(opcode, *args2, **kwargs)
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/proxy.py", line 591, in _request
    reply = self.iface.proxyreq(req, reboot=reboot, no_reply=no_reply, pre_reply=None)
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/proxy.py", line 357, in proxyreq
    return self.reply(self.REQ_PROXY)
  File "/Users/zhuowei/Documents/repos/m1n1/proxyclient/m1n1/proxy.py", line 256, in reply
    raise UartChecksumError()
m1n1.proxy.UartChecksumError
```

and finally, if I run shell.py again it works:

```
python3 shell.py 
TTY> usb-dwc3@382280000: ACM device closed
TTY> usb-dwc3@382280000: ACM device opened
m1n1 base: 0x8038dc000
Have fun!
>>> 

```

**Comment by marcan** [comment]
That normally happens if some error happened that triggered an exception message that stepped over the MMIOTrace code. Yesterday I just pushed a rework that finally makes handling such exceptions properly possible, can you try again? (remember to always chainload m1n1 before using the hypervisor; we do not support mixing versions).

FWIW, I tried your command line and it works fine for me, on a Mac Mini with the same kernel (though of course it panics due to not being able to mount the ramdisk).

Also, hint: you probably want to pass `serial=3` and cat the secondary m1n1 serial device to get the kernel log via serial instead of on the framebuffer. At least on my setup, XNU borks the HDMI output during the boot process so the single-user shell doesn't show up on there properly (not a hypervisor thing, it happens on bare metal too), but it works fine over serial. I think it's probably switching to a display mode that my capture card does not support or something like that.
