### ISSUE TITLE
Resizing error

### ISSUE THREAD

**Issue by kidandcat** [AsahiLinux/m1n1#186]
I got this error:

```
04-04 11:02 root         DEBUG    run: diskutil ('apfs', 'resizeContainer', 'disk0s2', '399999238144')
04-04 11:06 root         INFO     MSG: Failed to run process: diskutil apfs resizeContainer disk0s2 399999238144
04-04 11:06 root         ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 820, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 672, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 792, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 612, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '399999238144']' returned non-zero exit status 1.
```

[installer.log](https://github.com/AsahiLinux/m1n1/files/8408388/installer.log)

**Comment by kidandcat** [comment]
It looks like it is an issue with my mac as I cannot resize the partition with the disk utility neither
